google_maps_key: 'ABQICCCFECFEAE82qgb3Zc2YyS-oBT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSySz_REpPq-4WZA27OwgbtyR3Vc'
data_folder: 'sample_data/'
allowed_extensions: ['.gpx', '.nmea', '.kml']
admin_pass: 'wtfbbq'
db_connect_string: 'mysql://user:pass@mysql.example.com/runalog'
